package banco;

public class CoisasPfazer {
	
	
	
	
	
	
	
	/** 
	 * 
	 * VER PQ TA SALVANDO NULL O ESTADO NO BANCO!
	 * 
	 * Reload na tela filtro quando desmarcar alguma opção
	 * 
	 * VERIFICAR FILTRO TELA ADM E ARRUMAR TUDO(CONFERIR SE O FINALIZAR TA FUNFANDO)
	 * 
	 * CHECAR O ESQUECI A SENHA PARA VER SE TA TUDO OK
	 * 
	 * Arrumar legendas dos graficos(YAN)
	 * 
	 * FAZER O WEBSERVICE NO ANDROID PARA VERIFICAR O USUARIO*******
	 * 
	 * COLOCAR O LINK DO PROJETO NOS WEBVIEW E TESTAR
	 * 
	 * 
	 * 
	 * !!!!BUGS!!!!
	 * 
	 * 
	 * A TELA HISTORICO DIVIDE A PORRA DOS FILTROS NA 3 LINHA! WTF!(PEQUENO)
	 * 
	 * O FILTRO AO SER FINALIZADO OS CURRICULOS O CAMPO IDADE FICA EM ZERO ZERO(PEQUENO)
	 * 
	 * 
	 * 
	 * BUG PESADO, SE O CURRICULO DO ALUNO ESTA ABERTO EM OUTRA PAGINA, A PAGINA DO SISTEMA NÃO FUNCIONA(MEDIO)
	 * 
	 * SEMPRE Q A SENHA É ALTERADA ELE MATA A SESSAO E NADA FUNCIONA NO SISTEMA!(MEDIO)
	 * 
	 * ARRUMAR O CARALHO DO APP(MEDIO)
	 * 
	 * 
	 * FILTRO EMPRESA ESTA DANDO O FUCKING NO RECORDS FOUND(PESADO)
	 * 
	 * SE NÃO PREENCHER NADA NO FILTRO DA ERRO(PESADO)
	 * 
	 * 
	 * **/
	
	
	
	

	
	
	
	
	
	
	
	
	
	
	
	
	
	
	

}
