package banco;

public class CoisasPfazer {
	
	
	
	
	
	
	
	/** 
	 * 
	 * VER PQ TA SALVANDO NULL O ESTADO NO BANCO!
	 * 
	 * Reload na tela filtro quando desmarcar alguma opção
	 * 
	 * VERIFICAR FILTRO TELA ADM E ARRUMAR TUDO(CONFERIR SE O FINALIZAR TA FUNFANDO)
	 * 
	 * CHECAR O ESQUECI A SENHA PARA VER SE TA TUDO OK, E VER SE TEM GROW FALANDO Q MANDOU O EMAIL
	 * 
	 * 
	 * 
	 * FAZER O WEBSERVICE NO ANDROID PARA VERIFICAR O USUARIO*******
	 * 
	 * COLOCAR O WEBVIEW NO ANDROID PARA BUSCAR AS 2 TELAS
	 * 
	 * 
	 * !!!!BUGS!!!!
	 * 
	 * 
	 * BUGZINHO NO HISTORICO ADM, QUANDO LISTA O CURRICULO E VC CLICA NO FILTRO E VOLTA PRO HISTORICO E FINALIZA A TELA FICA BRANCA!
	 * 
	 * BUG PESADO, SE O CURRICULO DO ALUNO ESTA ABERTO EM OUTRA PAGINA, A PAGINA DO SISTEMA NÃO FUNCIONA
	 * 
	 * 
	 * **/
	
	
	
	

	
	
	
	
	
	
	
	
	
	
	
	
	
	
	

}
